import { Pregunta } from './pregunta';

export const MOCKPREGUNTAS : Pregunta[] = [
    { idPregunta: 1, glosa: 'Cual es el nombre:' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 2, glosa: 'Cual es su edad:' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 3, glosa: 'Cual es el nombre de su Madre',
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 4, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 5, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 6, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 7, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 8, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 9, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 10, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 11, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 12, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 13, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 14, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 15, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 16, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 17, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 18, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 19, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 20, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 21, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 22, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 23, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 24, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 25, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { idPregunta: 26, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""}
    
];
