import { Pregunta } from './pregunta';

export const MOCKPREGUNTAS : Pregunta[] = [
    { id: 1, glosa: 'Cual es el nombre:' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 2, glosa: 'Cual es su edad:' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 3, glosa: 'Cual es el nombre de su Madre',
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 4, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 5, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 6, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 7, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 8, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 9, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 10, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 11, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 12, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 13, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 14, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 15, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 16, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 17, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 18, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 19, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 20, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 21, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 22, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 23, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 24, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""},
    { id: 25, glosa: 'Es usted hombre o mujer' ,
    opciones : ['A','B','C','D'],respuesta : ""}
    
];
